### ISSUE TITLE
[Question] Sampling u for encryption

### ISSUE THREAD

**Issue by PascalStehling** [bit-ml/he-scheme#3]
Hi,
thanks for you Blog post and your code. Its really good, to get an understanding for rlwe. But there is one discrepancy with you Blog Post and your Code, with you encryption, which im not sure about.

In you Blog Post you write:
![image](https://github.com/bit-ml/he-scheme/assets/33455644/fc258f00-6abb-4665-9080-2baba069b924)

But in you code, you use the `gen_binary_poly` function to generate u, instead of `gen_normal_poly` like you did for the both e. Is that an error in you code or is there a good reason to do this?

Best Pascal

**Comment by mbolboceanu** [comment]
Hello,

Thank you for your feedback and interest in our blogpost and code, we are happy to hear. :)

About your question, thanks for pointing it out. :) It looks there is indeed a typo in the encryption part.
We considered, according to https://eprint.iacr.org/2012/144.pdf page 5, the randomness u used in the encryption sampled as the secret, from the binary distribution. The reason for this is because both s and u influence the noise growth in a fresh ciphertext. For this, you can take a look at the decryption equation or Lemma 1 from the paper above. If s and u are chosen as polynomials with small coefficients, the noise growth will also get small. :) This also helps to motivate the security of the scheme as based on the hardness of the Ring-LWE assumption with binary secret.
